package vista;

import Conexion.*;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AgregarCliente extends javax.swing.JFrame {

    public AgregarCliente(String telefono) {
        initComponents();
        setResizable(false);
        setFocusable(false);
        setLocationRelativeTo(null);
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/img/footer.png"));
        setIconImage(iconoApp.getImage());
        jTextField_telefono.setText(telefono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jButton_registrarse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_direccion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar cliente");
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 242, 211));
        jPanel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Dirección*:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 40));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Nombre(s):*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));

        jTextField_nombre.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPanel1.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 290, 40));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Telefono*:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 30));

        jTextField_telefono.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextField_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 280, 40));

        jButton_registrarse.setBackground(new java.awt.Color(61, 129, 254));
        jButton_registrarse.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrarse.setText("Registrar");
        jButton_registrarse.setBorder(null);
        jButton_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 200, 40));

        jTextArea_direccion.setColumns(20);
        jTextArea_direccion.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextArea_direccion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_direccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 330, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/revisar.png"))); // NOI18N
        jLabel2.setText("Ingrese los datos del cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarseActionPerformed
        String nombre = jTextField_nombre.getText();
        String telefono = jTextField_telefono.getText();
        String direccion = jTextArea_direccion.getText();

        if (nombre.isEmpty() || telefono.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Verificar que el número de teléfono tenga 10 dígitos
            if (telefono.length() != 10) {
                JOptionPane.showMessageDialog(null, "El número de teléfono debe tener exactamente 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;  // Salir del método si la validación falla
            }

            String query = "INSERT INTO Cliente (nombreCliente, telefono, direccion) VALUES (?, ?, ?)";
            try {
                Connection conexion = new GestionPizzasConexion().Conectar();
                PreparedStatement preparedStatement = conexion.prepareStatement(query);
                preparedStatement.setString(1, nombre);
                preparedStatement.setString(2, telefono);
                preparedStatement.setString(3, direccion);

                int rowsAffected = preparedStatement.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Cliente agregado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el Cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                }

                // Cerrar la conexión y el PreparedStatement
                preparedStatement.close();
                conexion.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al agregar el Cliente: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_registrarseActionPerformed

    private void jTextField_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonoKeyTyped
        // Obtener el texto actual del JTextField
        String telefono = jTextField_telefono.getText();

        // Verificar si ya hay 10 dígitos
        if (telefono.length() >= 10) {
            // Consumir el evento para que el carácter no se añada al JTextField
            evt.consume();
        }

        // Verificar si el carácter es un dígito
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            // Consumir el evento si no es un dígito
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_telefonoKeyTyped

    public void limpiar() {
        jTextField_nombre.setText("");
        jTextField_telefono.setText("");
        jTextArea_direccion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_direccion;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
