package vista;

import Conexion.*;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AgregarUsuario extends javax.swing.JFrame {

    public AgregarUsuario() {
        initComponents();
        setResizable(false);
        setFocusable(false);
        setLocationRelativeTo(null);
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/img/footer.png"));
        setIconImage(iconoApp.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_apellido = new javax.swing.JTextField();
        jCheckBox_ver_clave = new javax.swing.JCheckBox();
        jButton_registrarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Usuarios");
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 242, 211));
        jPanel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de usuario:*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 40));

        jTextField_usuario.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPanel1.add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 290, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Rol*:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 40));

        jPasswordField_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPasswordField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_passwordKeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 290, 40));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Nombre(s):*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        jTextField_nombre.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPanel1.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 290, 40));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Apellido(s):");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 30));

        jTextField_apellido.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jPanel1.add(jTextField_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 280, 40));

        jCheckBox_ver_clave.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jCheckBox_ver_clave.setText("Mostrar Contraseña");
        jCheckBox_ver_clave.setAlignmentX(50.0F);
        jCheckBox_ver_clave.setAlignmentY(50.0F);
        jCheckBox_ver_clave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox_ver_clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox_ver_clave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox_ver_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_ver_claveMouseClicked(evt);
            }
        });
        jCheckBox_ver_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ver_claveActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_ver_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jButton_registrarse.setBackground(new java.awt.Color(61, 129, 254));
        jButton_registrarse.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrarse.setText("Registrarse");
        jButton_registrarse.setBorder(null);
        jButton_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 200, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprobacion-de-usuario.png"))); // NOI18N
        jLabel2.setText("Ingrese los datos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistente", "Administrador" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarseActionPerformed
        String usuario = jTextField_usuario.getText();
        String nombre = jTextField_nombre.getText();
        String apellido = jTextField_apellido.getText();
        String rol = jComboBox1.getSelectedItem().toString();
        String password = new String(jPasswordField_password.getPassword());
        String hashedPassword = Login.hashSHA256(password); // Método estático

        if (usuario.isEmpty() || password.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String query = "INSERT INTO Usuarios (usuario, contraseña, rol, nombres, apellidos) VALUES (?, ?, ?, ?, ?)";
            try {
                Connection conexion = new GestionPizzasConexion().Conectar();
                PreparedStatement preparedStatement = conexion.prepareStatement(query);

                preparedStatement.setString(1, usuario);
                preparedStatement.setString(2, hashedPassword);
                preparedStatement.setString(3, rol);
                preparedStatement.setString(4, nombre);

                if (!apellido.isEmpty()) {
                    preparedStatement.setString(5, apellido);
                } else {
                    preparedStatement.setNull(5, java.sql.Types.VARCHAR); // Índice corregido
                }

                int rowsAffected = preparedStatement.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario agregado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al agregar el usuario: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton_registrarseActionPerformed

    public void limpiar() {
        jTextField_usuario.setText("");
        jTextField_nombre.setText("");
        jTextField_apellido.setText("");
        jPasswordField_password.setText("");
        jTextField_usuario.requestFocus();
    }

    private void jPasswordField_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwordKeyTyped

    }//GEN-LAST:event_jPasswordField_passwordKeyTyped

    private void jCheckBox_ver_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_ver_claveMouseClicked

    }//GEN-LAST:event_jCheckBox_ver_claveMouseClicked

    private void jCheckBox_ver_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ver_claveActionPerformed
        if (jCheckBox_ver_clave.isSelected()) {
            jPasswordField_password.setEchoChar((char) 0); // Mostrar contraseña
        } else {
            jPasswordField_password.setEchoChar('•'); // Ocultar contraseña
        }
    }//GEN-LAST:event_jCheckBox_ver_claveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_registrarse;
    private javax.swing.JCheckBox jCheckBox_ver_clave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_apellido;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
