package vista;

import Conexion.GestionPizzasConexion;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author ascen
 */
public class GestionarClientes extends javax.swing.JFrame {

    private Connection conexion;

    private DefaultTableModel dtm;
    private Object[] obj = new Object[4];
    private int filaSeleccionada;

    /**
     * Creates new form GestionarClientes
     */
    public GestionarClientes() {
        initComponents();
        cargarTablaCompletaClientes();
        setLocationRelativeTo(null);
        cargarNombresClientes();
         ImageIcon iconoApp = new ImageIcon(getClass().getResource("/img/footer.png"));
        setIconImage(iconoApp.getImage());
    }

    // Método para cargar la tabla de clientes
    public void cargarTablaCompletaClientes() {
        GestionPizzasConexion con = new GestionPizzasConexion();
        conexion = con.Conectar();
        DefaultTableModel modeloTabla = new DefaultTableModel();

        // Configurar las columnas de la tabla
        modeloTabla.addColumn("ID Cliente");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Dirección");

        // Consulta SQL para obtener los datos de los clientes
        String sql = "SELECT idCliente, nombreCliente, telefono, direccion FROM Cliente";

        try {
            Statement statement = conexion.createStatement();
            ResultSet resultado = statement.executeQuery(sql);

            // Llenar el modelo de la tabla con los datos de la consulta
            while (resultado.next()) {
                Object[] fila = new Object[4];
                fila[0] = resultado.getInt("idCliente");
                fila[1] = resultado.getString("nombreCliente");
                fila[2] = resultado.getString("telefono");
                fila[3] = resultado.getString("direccion");

                modeloTabla.addRow(fila);
            }

            // Asignar el modelo de la tabla
            jTable_clientes.setModel(modeloTabla);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla de clientes: " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Nuevo método para obtener los nombres de los clientes
    public void cargarNombresClientes() {
        try {
            GestionPizzasConexion con = new GestionPizzasConexion();
            conexion = con.Conectar();
            String consulta = "SELECT nombreCliente FROM Cliente";
            Statement statement = conexion.createStatement();
            ResultSet resultSet = statement.executeQuery(consulta);

            // Limpiar el JComboBox
            jComboBox_cliente.removeAllItems();

            // Agregar la opción por defecto
            jComboBox_cliente.addItem("Seleccione cliente");

            // Agregar los nombres de los clientes al JComboBox
            while (resultSet.next()) {
                String nombreCliente = resultSet.getString("nombreCliente");
                jComboBox_cliente.addItem(nombreCliente);
            }

            // Cerrar recursos
            resultSet.close();
            statement.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar nombres de clientes: " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jButton_eliminar = new javax.swing.JButton();

        setTitle("Información de los clientes");
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 242, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_clientes.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_clientesMouseClicked(evt);
            }
        });
        jTable_clientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable_clientesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_clientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 460));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.png"))); // NOI18N
        jLabel2.setText("Información de los clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 14))); // NOI18N

        jButton1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox_cliente.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_cliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_clienteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 240, 110));

        jButton_eliminar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_eliminar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.setBorderPainted(false);
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if (jComboBox_cliente.getSelectedIndex() ==0) {
            return;
        } else {
             cargarTablaFiltrada();
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_clienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_clienteItemStateChanged

    }//GEN-LAST:event_jComboBox_clienteItemStateChanged

    private void jTable_clientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable_clientesPropertyChange

        // Sólo nos interesa cuando se termina la edición de una celda
        if ("tableCellEditor".equals(evt.getPropertyName())) {
            if (!jTable_clientes.isEditing()) {
                // Obtenemos fila y columna editadas
                int fila = jTable_clientes.getSelectedRow();
                int columna = jTable_clientes.getSelectedColumn();

                // Obtenemos el modelo y el valor nuevo
                TableModel model = jTable_clientes.getModel();
                Object nuevoValor = model.getValueAt(fila, columna);

                // Obtenemos el idCliente de la primera columna (asumiendo que está en la columna 0)
                Object idClienteObj = model.getValueAt(fila, 0);
                if (idClienteObj == null) {
                    JOptionPane.showMessageDialog(this, "No se encontró el ID del cliente.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int idCliente = Integer.parseInt(idClienteObj.toString());

                // Determinamos el nombre de columna en la base de datos según el índice de la tabla
                String columnaBD;
                switch (columna) {
                    case 1:
                        columnaBD = "nombreCliente";
                        break;
                    case 2:
                        columnaBD = "telefono";
                        break;
                    case 3:
                        columnaBD = "direccion";
                        break;
                    default:
                        // Si es la columna 0 (id) o fuera de rango, no hacemos nada
                        return;
                }

                // Armamos y ejecutamos el UPDATE
                String sql = "UPDATE cliente SET " + columnaBD + " = ? WHERE idCliente = ?";
                try (PreparedStatement pst = conexion.prepareStatement(sql)) {
                    pst.setObject(1, nuevoValor);
                    pst.setInt(2, idCliente);
                    int afectados = pst.executeUpdate();

                    if (afectados > 0) {
                        System.out.println("Cliente #" + idCliente + " actualizado: "
                                + columnaBD + " = " + nuevoValor);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "No se pudo actualizar el cliente en la base de datos.",
                                "Error de actualización", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Error al actualizar la base de datos:\n" + ex.getMessage(),
                            "SQL Error", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_jTable_clientesPropertyChange

    private void jTable_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_clientesMouseClicked


    }//GEN-LAST:event_jTable_clientesMouseClicked

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        GestionPizzasConexion con = new GestionPizzasConexion();
        conexion = con.Conectar();
        // 1) Obtenemos la fila seleccionada
        int fila = jTable_clientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor selecciona un cliente para eliminar.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2) Recuperamos el idCliente de la columna 0
        TableModel model = jTable_clientes.getModel();
        Object idObj = model.getValueAt(fila, 0);
        int idCliente = Integer.parseInt(idObj.toString());

        // 3) (Opcional) Confirmación
        int confirma = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar al cliente?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }

        // 4) Aseguramos que la conexión esté abierta
        try {
            if (conexion == null || conexion.isClosed()) {
                conexion = con.Conectar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo reabrir la conexión:\n" + ex.getMessage(),
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5) Ejecutamos el DELETE
        String sql = "DELETE FROM cliente WHERE idCliente = ?";
        try (PreparedStatement pst = conexion.prepareStatement(sql)) {
            pst.setInt(1, idCliente);
            int afectados = pst.executeUpdate();
            if (afectados > 0) {
                // 6) Eliminamos la fila del modelo de la tabla
                DefaultTableModel dtm = (DefaultTableModel) jTable_clientes.getModel();
                dtm.removeRow(fila);
                JOptionPane.showMessageDialog(this,
                        "Cliente eliminado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el cliente en la base de datos.",
                        "Error al eliminar",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar en la base de datos:\n" + ex.getMessage(),
                    "SQL Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton_eliminarActionPerformed

    // Método para cargar la tabla de clientes filtrada por nombre
    public void cargarTablaFiltrada() {
        GestionPizzasConexion con = new GestionPizzasConexion();
        conexion = con.Conectar();
        DefaultTableModel modeloTabla = new DefaultTableModel();

        // Configurar las columnas de la tabla
        modeloTabla.addColumn("ID Cliente");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Dirección");

        // Consulta SQL para obtener los datos de los clientes filtrados por nombre
        String nombreSeleccionado = jComboBox_cliente.getSelectedItem().toString();
        String sql = "SELECT idCliente, nombreCliente, telefono, direccion FROM Cliente WHERE nombreCliente = ?";

        try {
            PreparedStatement preparedStatement = conexion.prepareStatement(sql);
            preparedStatement.setString(1, nombreSeleccionado);
            ResultSet resultado = preparedStatement.executeQuery();

            // Llenar el modelo de la tabla con los datos de la consulta
            while (resultado.next()) {
                Object[] fila = new Object[4];
                fila[0] = resultado.getInt("idCliente");
                fila[1] = resultado.getString("nombreCliente");
                fila[2] = resultado.getString("telefono");
                fila[3] = resultado.getString("direccion");

                modeloTabla.addRow(fila);
            }

            jTable_clientes.setModel(modeloTabla);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla filtrada: " + e, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JComboBox<String> jComboBox_cliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_clientes;
    // End of variables declaration//GEN-END:variables
}
