package vista;

import Conexion.*;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Properties;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public class Login extends javax.swing.JFrame {

    int idUsuario = 0;

    public Login() {

        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);

        // Establecer el icono de la aplicación
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/img/footer.png"));
        setIconImage(iconoApp.getImage());
        barra.setVisible(false);
        label_mensaje.setVisible(false);
        jLabel_porcentaje.setVisible(false);

    }

    /**
     * Método para actualizar la barra de progreso.
     */
    public void Actualizarbarra(int porcentaje, String mensaje) {

        label_mensaje.setVisible(true);
        jLabel_porcentaje.setVisible(true);
        if (porcentaje < 0 || porcentaje > 100) {
            JOptionPane.showMessageDialog(
                    this,
                    "Porcentaje inválido: " + porcentaje,
                    "Error de progreso",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (mensaje == null || mensaje.trim().isEmpty()) {
            mensaje = "Procesando...";
        }
        if (!barra.isVisible()) {
            barra.setVisible(true);
        }
        barra.setValue(porcentaje);
        label_mensaje.setText(mensaje);
        jLabel_porcentaje.setText(porcentaje + "%");
        barra.repaint();

        if (porcentaje == 100) {
            // Oculta la barra tras medio segundo para que se vea el 100%
            new Timer(2000, e -> barra.setVisible(false)).start();
            new Timer(2000, e -> label_mensaje.setVisible(false)).start();
            new Timer(2000, e -> jLabel_porcentaje.setVisible(false)).start();

        }

    }

    /**
     * Lógica normal de login/primer usuario (antes estaba en el constructor).
     */
    public void verificarYCrearPrimerUsuario() {
        GestionPizzasConexion conexion = new GestionPizzasConexion();
        Connection conn = conexion.Conectar();
        boolean existenUsuarios = false;

        try {
            existenUsuarios = hayUsuarios(conn);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error al comprobar usuarios: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            conexion.CerrarConexion();
            return;
        }

        if (!existenUsuarios) {
            try {
                crearPrimerUsuario(conn);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "❌ Error al crear primer usuario: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                conexion.CerrarConexion();
                return;
            }
        }
        conexion.CerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_password = new javax.swing.JPasswordField();
        jCheckBox_ver_clave = new javax.swing.JCheckBox();
        txt_usuario = new javax.swing.JTextField();
        jButton_olvidaste = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_iniciar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel_img = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        label_mensaje = new javax.swing.JLabel();
        jLabel_porcentaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 242, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_password.setBackground(new java.awt.Color(244, 244, 244));
        txt_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txt_password.setSelectionColor(new java.awt.Color(61, 129, 254));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 390, 40));

        jCheckBox_ver_clave.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jCheckBox_ver_clave.setText("Mostrar Contraseña");
        jCheckBox_ver_clave.setAlignmentX(50.0F);
        jCheckBox_ver_clave.setAlignmentY(50.0F);
        jCheckBox_ver_clave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox_ver_clave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox_ver_clave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox_ver_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ver_claveActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_ver_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, 15));

        txt_usuario.setBackground(new java.awt.Color(244, 244, 244));
        txt_usuario.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 390, 40));

        jButton_olvidaste.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton_olvidaste.setForeground(new java.awt.Color(60, 124, 241));
        jButton_olvidaste.setText("Olvidé mi contraseña.");
        jButton_olvidaste.setBorder(null);
        jButton_olvidaste.setBorderPainted(false);
        jButton_olvidaste.setContentAreaFilled(false);
        jButton_olvidaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_olvidaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_olvidasteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_olvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 390, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Carpizzio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 390, 30));

        jButton_iniciar.setBackground(new java.awt.Color(149, 201, 74));
        jButton_iniciar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_iniciar.setText("Iniciar sesión");
        jButton_iniciar.setBorderPainted(false);
        jButton_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 390, 40));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Nombre de usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabelMensaje.setFont(new java.awt.Font("Poppins Light", 2, 10)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(150, 179, 180));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 50, 20));

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificacion-de-escudo.png"))); // NOI18N
        jLabel18.setText("Iniciar sesión:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personaje.png"))); // NOI18N
        jPanel1.add(jLabel_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 490));

        barra.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        barra.setBorderPainted(false);
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 410, 10));

        label_mensaje.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        label_mensaje.setText("jLabel1");
        jPanel1.add(label_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, 30));

        jLabel_porcentaje.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel_porcentaje.setText("jLabel1");
        jPanel1.add(jLabel_porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Presionó Enter, mueve el foco al campo de texto txt_password
            jButton_iniciar.doClick();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void jCheckBox_ver_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ver_claveActionPerformed
        if (jCheckBox_ver_clave.isSelected()) {
            txt_password.setEchoChar((char) 0); // Mostrar contraseña
        } else {
            txt_password.setEchoChar('•'); // Ocultar contraseña
        }
    }//GEN-LAST:event_jCheckBox_ver_claveActionPerformed

    private void jButton_olvidasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_olvidasteActionPerformed
        JOptionPane.showMessageDialog(null, "Por favor, contacte al administrador para restablecer su contraseña.", "Olvidó su Contraseña", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_olvidasteActionPerformed

    private boolean hayUsuarios(Connection conn) throws SQLException {
        String consultaUsuarios = "SELECT * FROM usuarios";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(consultaUsuarios);

        boolean existenUsuarios = rs.next(); // true si hay al menos un registro
        rs.close();
        stmt.close();

        return existenUsuarios;
    }

    private void crearPrimerUsuario(Connection conn) throws SQLException {
        boolean existenDatosValidos = false;

        JOptionPane.showMessageDialog(
                null,
                "¡Bienvenido al Sistema de Pedidos de Pizza!\nGracias por usar nuestro software.\nVamos a crear el primer usuario para ingresar al sistema...",
                "Bienvenida",
                JOptionPane.INFORMATION_MESSAGE
        );

        while (!existenDatosValidos) {
            String nuevoUsuario = JOptionPane.showInputDialog(
                    null,
                    "Ingrese un nombre de usuario:",
                    "Crear primer usuario",
                    JOptionPane.WARNING_MESSAGE
            );

            String nuevaContraseña = JOptionPane.showInputDialog(
                    null,
                    "Ingrese una contraseña:",
                    "Crear primer usuario",
                    JOptionPane.WARNING_MESSAGE
            );

            // Validar que no sean null, vacíos ni "-1"
            if (nuevoUsuario != null && !nuevoUsuario.trim().isEmpty()
                    && nuevaContraseña != null && !nuevaContraseña.trim().isEmpty()
                    && !nuevaContraseña.trim().equals("-1")) {

                String insertarUsuario = "INSERT INTO usuarios (usuario, contraseña, rol) VALUES (?, ?, ?)";
                PreparedStatement psInsert = conn.prepareStatement(insertarUsuario);
                psInsert.setString(1, nuevoUsuario.trim());
                psInsert.setString(2, hashSHA256(nuevaContraseña));
                psInsert.setString(3, "Administrador");
                psInsert.executeUpdate();
                psInsert.close();

                JOptionPane.showMessageDialog(
                        null,
                        "Primer usuario creado correctamente.\nIngrese a continuación.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );
                existenDatosValidos = true;  // Sale del loop

            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Debe ingresar un usuario y una contraseña válidos.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                // El loop continúa
            }
        }
    }

    public static String hashSHA256(String input) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                hexString.append(String.format("%02x", b));
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error al encriptar con SHA-256", e);
        }
    }


    private void jButton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciarActionPerformed

        if (txt_password.getText().isEmpty() || txt_usuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        } else {

            String user = txt_usuario.getText().trim();
            String password = hashSHA256(txt_password.getText().trim());
            GestionPizzasConexion conexion = new GestionPizzasConexion();

            try {

                Connection conn = conexion.Conectar();
                // Proceder a verificar las credenciales
                String consulta = "SELECT id_usuario, usuario, contraseña FROM usuarios WHERE usuario = ? AND contraseña = ?";
                PreparedStatement prst = conn.prepareStatement(consulta);

                prst.setString(1, user);
                prst.setString(2, password);

                ResultSet rs = prst.executeQuery();

                if (rs.next()) {
                    idUsuario = rs.getInt("id_usuario");
                    

                    this.dispose();
                    Sistema sis = new Sistema(idUsuario);
                    sis.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
                }

                rs.close();
                prst.close();
                conexion.CerrarConexion();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton_iniciarActionPerformed


    private void txt_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Presionó Enter, mueve el foco al campo de texto txt_password
            txt_password.requestFocus();
        }
    }//GEN-LAST:event_txt_usuarioKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton jButton_iniciar;
    private javax.swing.JButton jButton_olvidaste;
    private javax.swing.JCheckBox jCheckBox_ver_clave;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabel_img;
    private javax.swing.JLabel jLabel_porcentaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_mensaje;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
